### ISSUE TITLE
Bonded-nested Polymorphic types get lost during deserialization in C#

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#71]
The primary problem this bug is trying to address is that the generic type parameter gets lost on a Clone action and so `IBonded<T>.Deserialize()` behaves differently depending on an object's level of nesting within the tree. For example, even though `src.Shapes[0] = new Bonded<Circle>(circle)`, the following returns false (and ideally it would return true).

    // false; "typeof(ShapeProps) != typeof(CircleProps)"
    Debug.Assert(
        src.Shapes[0].Deserialize().Props.Deserialize().GetType() ==
        circle.Props.Deserialize().GetType());

To illustrate this, I took the polymorphic_container.csproj sample and updated it to included polymorphic types nested within a bonded struct.

Expected:
  Polymorphic Bonded types Deserialize as the derived type they were created with where possible

Actual:
  Polymorphic Bonded types Deserialize only as the base type when nested inside another Bonded struct

IDL:

    namespace Examples

    enum Type
    {
        Unknown,
        Circle,
        Rectange
    }

    struct ShapeProps
    {
    }

    struct Shape
    {
        0: Type Type = Unknown;
        1: bonded<ShapeProps> Props;
    }

    struct Circle : Shape
    {
        0: double Radius;
    }

    struct CircleProps : ShapeProps
    {
        0: string CircleString;
    }

    struct Rectangle : Shape
    {
        0: double Width;
        1: double Height;
    }

    struct RectangleProps : ShapeProps
    {
        0: string RectangleString;
    }

Program.cs:

    static class Program
    {
        static void Main()
        {
            var circle = new Circle
            {
                Type = Type.Circle,
                Radius = 3.14,
                Props = new Bonded<CircleProps>(new CircleProps
                {
                    CircleString = "I'm a circle",
                }),
            };

            var rectangle = new Bonded<RectangleProps>(new Rectangle
            {
                Type = Type.Rectange,
                Width = 10,
                Height = 5.5,
                Props = new RectangleProps
                {
                    RectangleString = "I'm a rectangle",
                },
            });

            var src = new Polymorphic
            {
                Shapes = 
                {
                    new Bonded<Circle>(circle),
                    new Bonded<Rectangle>(rectangle)
                }
            };

            // ===
            // false; "typeof(ShapeProps) != typeof(CircleProps)"
            Debug.Assert(
                src.Shapes[0].Deserialize().Props.Deserialize().GetType() ==
                circle.Props.Deserialize().GetType());
            // ===

            // ... remainder omitted
        }
    }

**Comment by ranrav** [comment]
The props property of Shape is not bonded, so the behavior is by design. If you define it as bonded<ShapeProps> then the sub class will be serialized.

Sent from my Windows Phone
________________________________

**Comment by kylemc** [comment]
Ok. That looks right. I updated the code above to reflect that.

However, looking a little deeper, I realize what brought me down this path. In this example, the following two produce different outputs.

    src.Shapes[0].Deserialize().Props.Deserialize()

    /* is not equal to */

    circle.Props.Deserialize()

It would be really nice if Clone could preserve the derived generic parameter of the source instead of reverting to the base generic parameter.

**Comment by chadwalters** [comment]
Did you try using the Comparer rather than default equals? https://microsoft.github.io/bond/manual/bond_cs.html#comparer

**Comment by chadwalters** [comment]
Clone should be preserving the data; I think you may be handling things incorrectly on the deserialization side.

Is this the assert that you are saying fired?
Debug.Assert(Comparer.Equal(
                    src.Shapes[0].Deserialize().Props.Deserialize().GetType() ==
                    circle.Props.Deserialize().GetType());

I don't think you should be passing the result of GetType() to Comparer.

What about something like this?
Debug.Assert(Comparer.Equal(circle.props, shape.props as CircleProps);

**Comment by kylemc** [comment]
Thanks Chad. It's a definitely a corner case so I'll trying to explain it a little better. My scenario combines polymorphism, passthrough, and transcoding.

Here's some sample IDL (that should exhibit the problem).

    struct InnerBase {}

    struct Outer
    {
      0: bonded<InnerBase> Inner;
    }

    struct OuterBatch
    {
      0: vector<bonded<Outer>> Outers;
    }

Inner is bonded for polymorphism and Outer for passthrough. The problem is when I attempt to Transcode OuterBatch it deserializes/clones each Outer. This step loses the polymorphic type <T> of Inner. This isn't important when Inner is passthrough because the data isn't actually lost. However, when the Inner bonded is created from an object and cloned, the original type parameter is replaced with the base type parameter. At that point, the type of the original object is lost and IBonded<T>.Deserialize() only returns the base type.

The implementation I'm using in my own Bonded class to fix this is

        public override IBonded<U> Convert<U>()
        {
            if (typeof(U).GetTypeInfo().IsAssignableFrom(typeof(T).GetTypeInfo()))
            {
                return (IBonded<U>)this;
            }
            return new MyBonded<U>(...);
        }

**Comment by chadwalters** [comment]
OK, so this is not related to the program at the top of this issue then? As it stands, I don't think the program above exhibits the problem you are describing.

**Comment by kylemc** [comment]
Sorry for the confusion. A majority of the code above is from your polymorphic_container sample. I just took it and tweaked it until I got to the failure. This is the assertion I care about.

    // false; "typeof(ShapeProps) != typeof(CircleProps)"
    Debug.Assert(
        src.Shapes[0].Deserialize().Props.Deserialize().GetType() ==
        circle.Props.Deserialize().GetType());

If that returned true, then the problem would be fixed for my scenario as well. I'll clean up the first section to help clarify.

**Comment by kylemc** [comment]
Here's the workaround I've authored for use in our codebase.

```c#
    /// <summary>
    /// Implementation of <see cref="IBonded{T}"/> holding an instance of <typeparamref name="T"/>
    /// </summary>
    /// <remarks>
    /// This type is designed to be used in place of <see cref="Bond.Bonded{T}"/> in Bond.CSharp.3.0.6
    /// to fix github issue https://github.com/Microsoft/bond/issues/71. It will be deprecated as soon
    /// as a proper fix is available.
    /// </remarks>
    /// <typeparam name="T">Type representing a Bond schema</typeparam>
    public sealed class BondedWorkaround<T> : IBonded<T>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BondedWorkaround{T}"/> class
        /// </summary>
        /// <param name="value">Object of type <typeparamref name="T"/></param>
        public BondedWorkaround(T value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Gets the bonded value
        /// </summary>
        public T Value { get; private set; }

        T IBonded<T>.Deserialize()
        {
            return Clone<T>.From(this.Value);
        }

        U IBonded.Deserialize<U>()
        {
            if (this.Value is U)
            {
                return (U)(object)Clone<T>.From(this.Value);
            }
            return Clone<U>.From(this.Value as U);
        }

        void IBonded.Serialize<W>(W writer)
        {
            Serialize.To(writer, this.Value);
        }

        IBonded<U> IBonded.Convert<U>()
        {
            if (this.Value is U)
            {
                return (IBonded<U>)(IBonded)new BondedWorkaround<T>(this.Value);
            }
            return new BondedWorkaround<U>(this.Value as U);
        }
    }
```

**Comment by sapek** [comment]
Would you mind posting a link to your fork of the example with the changes to reproduce this?

**Comment by kylemc** [comment]
Here's the PR (to kylemc/bond/master)

https://github.com/kylemc/bond/pull/1/files

**Comment by sapek** [comment]
OK, that helped me understand. Thx.

[This](https://github.com/kylemc/bond/blob/313fa5d1aa5b6c1f1feda3eecacf24e6b76d2aef/examples/cs/core/polymorphic_container_issue71/program.cs#L97) is not how `bonded<T>` polymorphism works. `bonded<T>` doesn't know the actual C# type, it only knows `T`. It **can't** know the actual type because that is something that is language specific and Bond by design is a cross-language framework.

That is why in the `polymorphic_container` example the application [gets the schema type](https://github.com/Microsoft/bond/blob/f0d23a001df48bad01a401b2778647959f878b17/examples/cs/core/polymorphic_container/program.cs#L54) from the payload and [explicitly maps](https://github.com/Microsoft/bond/blob/f0d23a001df48bad01a401b2778647959f878b17/examples/cs/core/polymorphic_container/program.cs#L45-L49) it to appropriate C# type. You could do the same for the nested `bonded<T>`.

You workaround "works" only because you tried it on `bonded<T>` initialized with an object instance. The type information is still there. When `bonded<T>` is deserialized from payload there is no object instance and thus no type information.

I'm closing the issue since the behavior is by design. I'll take a look at the documentation to see how I can make all of this it more clear.

**Comment by kylemc** [comment]
No. This isn't an issue of misunderstanding (though it never hurts to improve docs).

I explicitly want a way to get my object back out of a Bonded<T>. This issue only applies to the object instance implementation. The passthrough implementation works just fine. Specifically, there are two scenarios where I think this will be advantageous.

First, the assertions I wrote in the sample are very similar to ones I'd write in unit tests. Having a natural "retrieval" for in-memory use simplifies testing.

Second, I use the Json.Net for JSON serialization and my implementation also requires non-lossy "retrieval" to successfully serialize structs (with nested bonded types).

If you take a look at my workaround, it strives to preserve the instance type whenever possible without changing the polymorphism semantics around bonded<T>.

**Comment by sapek** [comment]
You are right. I still misunderstood the problem. And yes, this is a bug in `Bonded<T>`, it performs unnecessary casts. Here is suggested fix: 5c09e9c6e131df10fd31679e48ee767574d847e3.

**Comment by kylemc** [comment]
Looks good to me

**Comment by sapek** [comment]
Fixed with 5c09e9c

**Comment by sucaritas** [comment]
this is still broken for me. has this change made it to the nugget package at nugget.org?
I am currently using package v5.20

I have cloned the repo and build and can repro this issue in the samples project
under "polymorphic_container". with code similar to kylemc.

**Comment by chwarr** [comment]
The fix was first released in 4.0.1, so 5.2.0 is sufficient. There may be something else going on here...

Can you share the code that's causing this problem? If you just want to fork Bond and push your modifications to polymorphic_container to you GitHub fork, I can look at it there.

**Comment by sucaritas** [comment]
Sorry but I am ki



and new to GitHub, I created a branch locally but I cant seem to put it in git hub.  so I am pasting the code here. this is for the polymorphic_container example

PROGRAM.CS
```csharp
namespace Examples
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using Bond;
    using Bond.Protocols;
    using Bond.IO.Unsafe;

    static class Program
    {
        static void Main()
        {
            var circle = new Circle
            {
                Type = Type.Circle,
                Radius = 3.14,
                ShapSubObject = new Bonded<SubObject>(new CircleSubObject() { AIntProp = 1 })
            };

            var rectangle = new Rectangle
            {
                Type = Type.Rectange,
                Width = 10,
                Height = 5.5,
                ShapSubObject = new Bonded<SubObject>(new RectangleSubObject() { ADoubleProp = 1.2 })
            };

            var src = new Polymorphic
            {
                Shapes = 
                {
                    new Bonded<Circle>(circle),
                    new Bonded<Rectangle>(rectangle)
                }
            };

            var output = new OutputBuffer();
            var writer = new CompactBinaryWriter<OutputBuffer>(output);

            Serialize.To(writer, src);

            var input = new InputBuffer(output.Data);
            var reader = new CompactBinaryReader<InputBuffer>(input);

            var dst = Deserialize<Polymorphic>.From(reader);

            var deserializers = new Dictionary<Type, Deserializer<CompactBinaryReader<InputBuffer>>>
            {
                {Type.Circle, new Deserializer<CompactBinaryReader<InputBuffer>>(typeof(Circle))},
                {Type.Rectange, new Deserializer<CompactBinaryReader<InputBuffer>>(typeof(Rectangle))}
            };
            
            foreach (var item in dst.Shapes)
            {
                // Deserialize item as Shape and extract object type
                var type = item.Deserialize().Type;
                
                // Select one of the precreated deserializers based on the item type
                var shape = deserializers[type].Deserialize(item);
                
                if (shape.GetType() == typeof(Circle))
                {
                    //Debug.Assert(Comparer.Equal(circle, shape as Circle));
					var sub = shape.ShapSubObject.Deserialize<CircleSubObject>();
                    Debug.Assert(sub.AIntProp == 1);
                }

                if (shape.GetType() == typeof(Rectangle))
                {
                    //Debug.Assert(Comparer.Equal(rectangle, shape as Rectangle));
                    var sub = shape.ShapSubObject.Deserialize<RectangleSubObject>();
                    Debug.Assert(sub.ADoubleProp == 1.2);
                }

                // Alternatively the generic method IBonded<T>.Deserialize<U> can be used
                if (type == Type.Circle)
                {
                    var c = item.Deserialize<Circle>();
                    Debug.Assert(Comparer.Equal(circle, c));
                }

                if (type == Type.Rectange)
                {
                    var r = item.Deserialize<Rectangle>();
                    Debug.Assert(Comparer.Equal(rectangle, r));
                }
            }
        }
    }
}
```

SCHEMA.BOND
```csharp
namespace Examples

enum Type
{
    Unknown,
    Circle,
    Rectange
}

struct SubObject
{

}

struct Shape
{
    0: Type Type = Unknown;
    1: bonded<SubObject> ShapSubObject;
}

struct Circle : Shape
{
    0: double Radius;
}

struct Rectangle : Shape
{
    0: double Width;
    1: double Height;
}

struct CircleSubObject : SubObject
{
    0: uint32 AIntProp;
}

struct RectangleSubObject : SubObject
{
    0: double ADoubleProp;
}

struct Polymorphic
{
    0: vector<bonded<Shape>> Shapes;
} 
```
you will see that the assert for AIntProp will fail because the value is 0 and not the expected 1

**Comment by chwarr** [comment]
No worries. The code here is enough. 

Lines like the following are causing the behavior that you're seeing:

```
ShapSubObject = new Bonded<SubObject>(new CircleSubObject() { AIntProp = 1 })
```

This says to Bond, created me a Bonded object with type `SubObject` that happens to be backed by a `CircleSubObject` instance. A `CircleSubObject` is a `SubObject`, so this type checks in C#. When serializing a Bond object with type `SubObject`, only the `SubObject` fields are written, because that's the type that you asked to be serialized.

On the other hand, code like the following creates a Bonded object with type `CircleSubObject`. An `IBonded<CircleSubObject>` is covariant with `IBonded<SubObject>`, so the assignment to `ShapSubObject` field type checks in C#. Now, when serializing the Bond object with type `CircleSubObject`, the `AIntProp` will be serialized as expected.

```
ShapSubObject = new Bonded<CircleSubObject>(new CircleSubObject() { AIntProp = 1 })
```

This is an easy mistake to make, so I think we should consider adding a more friendly API, [`Bonded<T>.From(T obj)`](https://github.com/Microsoft/bond/issues/416).

Note that `Comparer.Equal` recursively compares (effectively) via `operator==`. But, the implementation of `operator==` for Bonded performs a reference comparison, so the `Debug.Assert(Comparer.Equal(...))` assertions will fail, as the Bonded fields are different objects. (There's no good way to implement structural equality on Bonded instances.)

Hope this helps.

**Comment by sucaritas** [comment]
Yes this help quite a bit.
now that you have explained it of course it makes sense. I don't know if I would have immediately made the jump to Bonded<SubObject> creates a serialization that only takes in consideration SubObject properties. Now that write it down it makes sense, but at the time I was filling in the initialization of the Circle/Rectangle object, which has a Bonded<SubObject> property to it. And was not thinking of the serialization/deserialization consequences of the line 

new Bonded<SubObject>(new CircleSubObject() { AIntProp = 1 })

again thank you for clearing this up, and sorry for reviving this old bug's thread.
